name: Build

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build core
      working-directory: ./simple-si-units-core
      run: cargo build --verbose
    - name: Build macros
      working-directory: ./simple-si-units-macros
      run: cargo build --verbose
    - name: Build
      working-directory: ./simple-si-units
      run: cargo build --verbose --all-features
